#!/bin/bash

# ------------------------------------------------------------------------------
# File        : run-qemu.sh
#
# Description : Launch script for running the Buildroot-generated ARM64 Linux
#               image inside QEMU (qemu-system-aarch64).
#
# Purpose     : Boots the generated kernel and root filesystem in a virtual
#               ARM64 environment with networking and port forwarding enabled.
#
# Host Port Forwarding:
#   10022 -> Guest SSH (22)
#   9000  -> Guest application/server port
#
# Author      : Rajkumar Saravanakumar
# ------------------------------------------------------------------------------

# Launch QEMU ARM64 virtual machine using the Buildroot-generated image
qemu-system-aarch64 \
    # Machine type: ARM virtual platform
    -M virt  \
    
    # CPU configuration: Cortex-A53, single core
    -cpu cortex-a53 -nographic -smp 1 \

    # Kernel image generated by Buildroot
    -kernel buildroot/output/images/Image \

    # Kernel boot arguments:
    # root device = virtio block device
    # console output redirected to serial
    -append "rootwait root=/dev/vda console=ttyAMA0" \

    # Networking:
    # User-mode networking with port forwarding:
    # 10022 -> SSH
    # 9000  -> application/server
    -netdev user,id=eth0,hostfwd=tcp::10022-:22,hostfwd=tcp::9000-:9000 \

    # Attach virtual network interface
    -device virtio-net-device,netdev=eth0 \

    # Root filesystem disk image (ext4)
    -drive file=buildroot/output/images/rootfs.ext4,if=none,format=raw,id=hd0 \

    # Attach block device + random number generator
    -device virtio-blk-device,drive=hd0 -device virtio-rng-pci